server:
  port: 9192


spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  application:
    name: ORDER-SERVICE

#logging:
#  file: F:\log\microservices.log
#  file: C:/Users/Anil/OneDrive/Desktop/elk-stack.txt
logging:
  file:
    name: F:/log/microservices.log
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost
